### PR TITLE
Adding option for missing values

### PR DESCRIPTION
**Pull request by trevorgor289**
I wasn't sure how to properly deal with the merge issues on my last pull request, so I closed it and submitted a new pull request.

As a reminder, these were the changes I made:

I added two lines of code to the 'read_and_aggregate' function that fills any empty values in the CSV file with the desired 'filler' value selected by the user. The value can be entered as one of the functions arguments. Also, the part of the function checking for values 'out of range' did not work for me, so I added new lines of code to check that would check for 'out of range' values for both 'str' and 'int' datatypes.

and yes, it should be able to handle either int or str values.

### CODE REVIEW

**Comment by adrien-cotte** [comment]
Thanks, I gonna check it all :-)

**Comment by adrien-cotte** [comment]
Hum... I cannot understand but I have an issue.

I've put so debug prints:

```python
        print(df)
        df = df.fillna(empty_value_filler).astype(int)
        print(df)
```

Then `majority_judgment.py -c examples/resto.csv`:

```
   Pataterie  Burger King  3 Brasseurs  Soleil Italien  Régent
0        3.0          1.0          3.0             2.0     1.0
1        3.0          1.0          4.0             3.0     1.0
2        3.0          2.0          5.0             4.0     1.0
3        4.0          2.0          5.0             4.0     2.0
4        4.0          3.0          5.0             4.0     2.0
5        4.0          3.0          5.0             5.0     3.0
6        NaN          NaN          NaN             NaN     NaN
   Pataterie  Burger King  3 Brasseurs  Soleil Italien  Régent
0          3            1            3               2       1
1          3            1            4               3       1
2          3            2            5               4       1
3          4            2            5               4       2
4          4            3            5               4       2
5          4            3            5               5       3
6          0            0            0               0       0
```

Why I see `0` instead of `3` 🤔?

**Comment by adrien-cotte** [comment]
Ok, I got it.

You have placed `empty_value_filler=3` argument right after `category_names` but after the #31 PR we added `ignore_first_column=False` with @RomainDereu 

So, the following call is wrong:

```python
results = read_and_aggregate_csv(args.csv, category_names, args.ignore_first_column, args.type)
```

So, in your last commit, the `empty_value_filler` value is `args.ignore_first_column` .

Just change this in your commit:

```python
def read_and_aggregate_csv(file_path, category_names , empty_value_filler=3, ignore_first_column=False, values_type="int"):
```

By this:

```python
def read_and_aggregate_csv(file_path, category_names, ignore_first_column=False, values_type="int", empty_value_filler=3):
```

**Comment by trevorgor289** [comment]
Ok, no problem.

**Comment by adrien-cotte** [comment]
Nice, do you want to stop now or continue to add the `--empty-default-value` option?

**Pull request merged**
